[project]
name = "cwade-compmeth-cuny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charlie Wade", email = "charliew0707@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
]

[project.scripts]
cwade-compmeth-cuny = "cwade_compmeth_cuny:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
